services:
  vv:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - '5080:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword

  mysql:
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vv
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - db_data:/var/lib/mysql
  node:
    build:
      dockerfile: Dockerfile.node
    working_dir: /app
    user: "${UID}:${GID}"
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - '5000:3000'
    env_file:
      - ./.env

volumes:
  db_data:
