services:
  vv:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
  node:
    image: node:alpine
    working_dir: /app
    user: "${UID}:${GID}"
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    command: sh -c "npm install && npm run dev"
