services:
  vv:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
  node:
    build:
      dockerfile: Dockerfile.node
    working_dir: /app
    user: "${UID}:${GID}"
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - '5000:3000'
    env_file:
      - ./.env

